docs(aws): updates per single-node/multi-node scenarios
fermyon/installer pull request #116
Opened 2022-11-30 17:51 UTC by vdice

Some AWS-related docs updates/re-org following https://github.com/fermyon/installer/pull/100 cc @FrankYang0529

2022-12-07 17:50 UTC, michelleN reviewed
I need to look into where / how spin uses Hippo username and password.

2022-12-07 17:50 UTC, michelleN commented on aws/README.md
> +(see the configuration details mentioned below). Additionally, when Let's Encrypt
Would add `(LE)` after `Let's Encrypt` since we're using the abbreviation later for folks who aren't familiar.

2022-12-07 17:50 UTC, michelleN commented on aws/README.md
> +`0.0.0.0/0` aka The Entire Internet.
lol `The Entire Internet` 😂

2022-12-07 17:50 UTC, michelleN commented on aws/README.md
> +Once on the instance, output from user-data.sh can be checked like so:
what is `user-data.sh`?

2022-12-07 19:06 UTC, vdice commented on aws/README.md
> +    export HIPPO_URL=https://hippo.52.44.146.193.sslip.io
I'm unsure if this area can be updated/improved with a different approach introduced in recent Spin releases -- but for the purposes of `spin login`, I believe `HIPPO_URL` is still needed.

2022-12-07 19:06 UTC, vdice commented on aws/README.md
> +Once on the instance, output from user-data.sh can be checked like so:
Thank you, I've added a clarification here.

2022-12-07 19:07 UTC, vdice commented on aws/README.md
> +(see the configuration details mentioned below). Additionally, when Let's Encrypt
I've updated the text here to just remove the `LE` mention...

2022-12-09 17:39 UTC, vdice commented
@michelleN I believe I've addressed all comments -- let me know if there are any others to look at.  Thank you!

2022-12-09 20:58 UTC, michelleN approved these changes

2022-12-09 21:02 UTC, michelleN commented on aws/terraform/multiple-nodes/README.md
>  First, navigate to the `terraform` directory and initialize Terraform:
Is this section still accurate? I don't see a terraform dir in this dir and the terrform dir two levels up contains two other dirs not a terraform script.

2022-12-09 21:04 UTC, michelleN requested changes

2022-12-09 21:04 UTC, michelleN commented on aws/terraform/multiple-nodes/README.md
>  First, navigate to the `terraform` directory and initialize Terraform:
I think this should be `terraform/multiple-nodes`?

2022-12-09 21:09 UTC, vdice commented on aws/terraform/multiple-nodes/README.md
>  First, navigate to the `terraform` directory and initialize Terraform:
Good catch!  Both scenario READMEs should now be updated.

2022-12-09 22:45 UTC, michelleN approved these changes

2022-12-09 22:56 UTC, merged