Civo provider for Fermyon
fermyon/installer pull request #120
Opened 2022-12-22 06:52 UTC by saiyam1814

Signed-off-by: Saiyam Pathak <saiyam911@gmail.com>
Civo provider for Fermyon

2022-12-22 16:28 UTC, vdice commented
Hi @saiyam1814, thank you for the PR!  Excited to add another provider to this project.

For those of us new to Civo, could you supply a bit of info/background on the service?

Definitely eager to test this out; does Civo offer a free trial?

2022-12-22 17:49 UTC, saiyam1814 commented
Hi @vdice 
Civo is a cloud native service provider that provides managed Kubernetes similar to EKs, AKS etc.
We also have Compute, Object storage, Loadbalancer and Soon coming DbaaS.
We have terraform, pulumi, crossplane provider and also our cluster launch times are less than 90 seconds. 
With regions in NYC, FRA and LON and epic launch times we are only pure play Kubernetes that uses power of Kubernetes for managing customer clusters. 
also Matt is a friend and I am tech enthusiast who loves to learn new stuff and always looking to make things work with Civo. With this effort, Fermyon can be installed easily on the compute. 
I did test the flow as well.

2022-12-22 17:49 UTC, saiyam1814 commented
when you signup just ping me, on signup you do get $250 that you can use to test our civo

2022-12-23 21:18 UTC, vdice reviewed
@saiyam1814 Wanted to submit an initial review as I may not have a chance to test this on Civo before the holidays (I'll be out next week, returning in January).

This all looks great on a first pass, only a few minor suggestions.  Also, can you add a mention of this Civo installer scenario along with the others on the [README.md](https://github.com/fermyon/installer/blob/main/README.md)?

2022-12-23 21:18 UTC, vdice commented on civo/terraform/providers.tf
> +civo = {
nit: spacing on this line :)
```suggestion
    civo = {
```

2022-12-23 21:18 UTC, vdice commented on civo/README.md
> +## SSH into the Droplet instance
```suggestion
## SSH into the Civo instance
```

2022-12-23 21:18 UTC, vdice commented on civo/README.md
> +root@fermyon:~$ tail -n15 /var/log/cloud-init-output.log
Is `/var/log/cloud-init-output.log` the correct path where output from the startup.sh script is logged on a Civo instance?

2022-12-23 21:18 UTC, vdice commented on civo/terraform/outputs.tf
> +  description = "The public key for SSH access to the Droplet instance"
```suggestion
  description = "The public key for SSH access to the Civo instance"
```
(Same for the other occurrences elsewhere in this file.)

2022-12-25 07:24 UTC, saiyam1814 commented on civo/README.md
> +root@fermyon:~$ tail -n15 /var/log/cloud-init-output.log
Yes

2022-12-25 07:24 UTC, saiyam1814 commented
@vdice Done all the changes that you requested :)

2023-01-03 04:38 UTC, saiyam1814 commented
@vdice were you able to test it or facing any issues ? please let me know. was thinking I can out out a tweet for this once merged :)

2023-01-03 16:50 UTC, vdice commented
Happy New Year @saiyam1814!  I'm back today and will revisit this asap.

2023-01-04 00:08 UTC, vdice requested changes
@saiyam1814 I had a chance to test with my Civo account.  I'm liking my first experience :)

I ran into a few small issues; would be great to get fixes in prior to merge here.  Let me know what you think.

2023-01-04 00:08 UTC, vdice commented on civo/terraform/outputs.tf
> +  value       = civo_instance.spin.public_ip
I believe this should be `civo_reserved_ip.lb.ip`, right?

Otherwise, the spin instance public ip is provided, which doesn't appear to get the same ingress/egress rules as created in the firewall.

When I installed, I had the following outputs:
```
<snip>
bindle_url = "http://bindle.212.2.244.197.sslip.io/v1"
hippo_url = "http://hippo.212.2.244.197.sslip.io"
public_ip_address = "212.2.241.224"
```

(Note the different ip)

An ssh attempt would thus time out when using the public_ip_address as provided above:
```
ssh -i /tmp/civo_ssh_private_key root@$(terraform output -raw public_ip_address)
ssh: connect to host 212.2.241.224 port 22: Operation timed out
```

But when I used the reserved ip (as the hipp/bindle urls do), all is well:
```
$ ssh -i /tmp/civo_ssh_private_key root@212.2.244.197
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-132-generic x86_64)
<snip>
```

2023-01-04 00:08 UTC, vdice commented on civo/terraform/main.tf
> +  ingress_rule {
Here we only open 443, which works great when we `enable_letsencrypt` is true and the services run on https, but when `enable_letsencrypt` is false, we'd need to open 80 as the services run on http.

If we'd like, we can conditionalize this, similar to the other installers.  Check out the aws terraform here: https://github.com/fermyon/installer/blob/main/aws/terraform/single-node/main.tf#L165-L185

2023-01-04 05:07 UTC, saiyam1814 commented on civo/terraform/outputs.tf
> +  value       = civo_instance.spin.public_ip
Agree, made the changes

2023-01-04 05:08 UTC, saiyam1814 commented on civo/terraform/main.tf
> +  ingress_rule {
Added 80 as well

2023-01-04 05:08 UTC, saiyam1814 reviewed
All requested changed has been committed.

2023-01-04 17:33 UTC, vdice approved these changes
@saiyam1814 thank you for this addition! 🚀

2023-01-04 17:35 UTC, merged